# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/ilyaluk/atlantis-plan-ui:{{ .Version }}-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/ilyaluk/atlantis-plan-ui:{{ .Version }}-arm64v8
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
    goos: linux
    goarch: arm64
    goamd64: v1
    use: buildx

docker_manifests:
  - name_template: ghcr.io/ilyaluk/atlantis-plan-ui:{{ .Version }}
    image_templates:
      - ghcr.io/ilyaluk/atlantis-plan-ui:{{ .Version }}-amd64
      - ghcr.io/ilyaluk/atlantis-plan-ui:{{ .Version }}-arm64v8

changelog:
  disable: true
